### ISSUE TITLE
son muy parecidas las funciones

### ISSUE THREAD

**Issue by lspigariol** [pdepmartestm/2019-tpfi-rcomesan#2]
https://github.com/pdepmartestm/2019-tpfi-rcomesan/blob/0d2772ac82631a47536c08f57391ddb2b3fef2f3/piratas.hs#L45

**Comment by rcomesan** [comment]
Es verdad, lo cambié para que use [orden superior](https://github.com/pdepmartestm/2019-tpfi-rcomesan/blob/ac2619296355718f6ce966ee4342f97d559b7ef7/piratas.hs#L47). Gracias.
