### ISSUE TITLE
revisar parametros

### ISSUE THREAD

**Issue by lspigariol** [pdepmartestm/2019-tpfi-rcomesan#3]
https://github.com/pdepmartestm/2019-tpfi-rcomesan/blob/0d2772ac82631a47536c08f57391ddb2b3fef2f3/piratas.hs#L101

cambiando el orden de los parametros en la funcion te ahorras la expresion lambda

**Comment by rcomesan** [comment]
Es verdad, corregido en ac2619296355718f6ce966ee4342f97d559b7ef7. Gracias.
