### ISSUE TITLE
muy bien

### ISSUE THREAD

**Issue by lspigariol** [pdepmartestm/2019-tpfi-rcomesan#4]
el tp esta muy bien,

el abordaje de barco, la segunda opcion, es muy poco funcional.

**Comment by rcomesan** [comment]
Hola Lucas, gracias por las correcciones y perdón por la demora, no me llegó la notificación. Ya subí los cambios sugeridos.

**Comment by rcomesan** [comment]
Es verdad, la segunda es bastante fulera, la borré en 61584e5ee288cba3e7eaf8456b1d23dc77b4d551 y dejé la principal que tiene más sentido. @lspigariol
